---
title: "Marvel Network"
output: html_document
---

待解决：
边权重设置
同类对象聚集测试
聚类测试
可视化：ggraph、ggnet2、ggnetwork、network3D、visNetwork

```{r}
library(igraph)
library(tidyverse)
library(parallel)
library(microbenchmark)
library(ggraph)
```

```{r 点数据导入}
nodes <- read_csv('../../../Kaggle/Marvel networks/nodes.csv') #表明每个点是hero还是comic
nodes
str(nodes)
table(nodes$type) #6439个hero，12651个comic
```

```{r 边数据导入}
edges <- read_csv('../../../Kaggle/Marvel networks/edges.csv')  #每个hero在什么comic中出现
edges
str(edges)
length((unique(edges$hero)))  #6439
length((unique(edges$comic))) #12651
edges %>% 
  group_by(hero) %>% 
  count() %>% 
  arrange(desc(n))
```

```{r 点属性设置}
#一个hero可能对应多个comic，随机取一条
set.seed(1)
edges %>% 
  group_by(hero) %>% 
  sample_n(1) -> edges_1   #随机选择一条
edges_1                    #每个hero对应1个comic
```


```{r 网络数据导入}
hero_network <- read_csv('../../../Kaggle/Marvel networks/hero-network.csv')
hero_network
str(hero_network)                   #574467个关系,和理论总数579171相比缺失了一部分关系
length(unique(hero_network$hero1))
length(unique(hero_network$hero2))
```

```{r 清理edge1数据}
setdiff(hero_network$hero1, edges_1$hero)
setdiff(hero_network$hero2, edges_1$hero)
length(setdiff(hero_network$hero1, edges_1$hero)) #有3个不在egdes_1中
length(setdiff(hero_network$hero2, edges_1$hero)) #有3个不在egdes_1中

edges_1 %>% filter(str_detect(hero, "SABRE")) %>% group_by(hero) %>% count()
hero_network %>% filter(str_detect(hero1, "SABRE")) %>% group_by(hero1) %>% count()
edges_1 %>% filter(str_detect(hero, "BLADE")) %>% group_by(hero) %>% count()
hero_network %>% filter(str_detect(hero1, "BLADE")) %>% group_by(hero1) %>% count()
edges_1 %>% filter(str_detect(hero, "SPIDER-MAN/PETER PAR")) %>% group_by(hero) %>% count()
hero_network %>% filter(str_detect(hero1, "SPIDER-MAN/PETER PAR")) %>% group_by(hero1) %>% count()

edges_1 %>% 
  mutate(hero_c = str_replace_all(hero, c("^SABRE/$" = "SABRE", 
                                          "^BLADE/$" = "BLADE", 
                                          "^SPIDER-MAN/PETER PARKER$" = "SPIDER-MAN/PETER PAR"))) %>% 
  ungroup() %>% 
  select(-hero) %>% 
  rename(hero = hero_c) %>% 
  select(hero, comic) -> edges_1_clear
edges_1_clear
edges_1_clear %>% filter(str_detect(hero, "SABRE")) %>% group_by(hero) %>% count()
edges_1_clear %>% filter(str_detect(hero, "BLADE")) %>% group_by(hero) %>% count()
edges_1_clear %>% filter(str_detect(hero, "SPIDER-MAN/PETER PAR")) %>% group_by(hero) %>% count()

# hero_network %>% 
#   inner_join(edges_1, by = c("hero1" = "hero")) %>% 
#   inner_join(edges_1, by = c("hero2" = "hero")) %>% 
#   select(hero1, hero2) -> hero_network_com
# hero_network_com

setdiff(hero_network$hero1, edges_1_clear$hero)
setdiff(hero_network$hero2, edges_1_clear$hero)
length(setdiff(hero_network$hero1, edges_1_clear$hero))
length(setdiff(hero_network$hero2, edges_1_clear$hero))
```

```{r 重复关系处理}
hero_network %>% distinct() -> hero_network_dis  #转换网络之前处理数据框
hero_network_clear <- hero_network_dis[!duplicated(t(apply(hero_network_dis, 1, sort))),] %>% 
  filter(hero1 != hero2) #删除两个hero相同的关系,167100
hero_network_clear 
```


```{r}
# microbenchmark(
#   par = hero_network[!duplicated(t(parApply(makeCluster(detectCores()), hero_network, 1, sort))),],
#   seq = hero_network[!duplicated(t(apply(hero_network, 1, sort))),],
#   times = 10,
#   unit = "s"
# )
```


```{r 数据框转化为网络数据}
net <- graph_from_data_frame(hero_network_clear, directed = FALSE, vertices = edges_1_clear) #第一列一定要是vertex的名称，否则会报错
net
list.vertex.attributes(net)
get.vertex.attribute(net, "comic", "LITTLE, ABNER")
```

```{r 重复关系处理方法2}
net_origin <- graph_from_data_frame(hero_network, directed = FALSE) #先转为网络，再进行精简
net_origin
net_sim <- igraph::simplify(net_origin)  #去除重复关系(在无向图中不论位置)和自连接，与方法1相差了自循环的12条，比方法1更高效
net_sim #167100
```

```{r}
E(net_origin)$weight
E(net_sim)$weight
```


```{r 网络基本信息}
gorder(net)         #点数量
gsize(net)          #边数量
```


```{r 点中心性分析}
net %>% degree() %>% sort(decreasing = T) %>% head(10)               #度中心性
net %>% betweenness() %>% sort(decreasing = T) %>% head(10)          #中介中心性
net %>% closeness() %>% sort(decreasing = T) %>% head(10)            #接近中心性
eigen_centrality(net)$vector %>% sort(decreasing = T) %>% head(10)   #特征向量中心性
```


```{r 网络距离}
diameter(net)            #全局最长距离
get_diameter(net)        #全局最长路径
farthest_vertices(net)   #全局最长路径起终点及距离
mean_distance(net)       #平均距离
shortest_paths(net, from = "CAPTAIN AMERICA", to = "WOLVERINE/LOGAN")  #两点间最短路径
distances(net, v = "CAPTAIN AMERICA", to = "WOLVERINE/LOGAN")  #两点之间的最短距离，同shortest.paths
eccentricity(net, vids = "CAPTAIN AMERICA")        #特定点离心率，到各点距离最大值
```


```{r 网络紧密及联通程度}
edge_density(net)                   #网络密度
reciprocity(net)                    #双向关系占比，无向图=1
transitivity(net, type = "global")  #完整三角关系占比，也称为聚类系数
```


```{r 网络微观结构}
dyad_census(net)      #二元关系，分为相互、单向和无关系3种类型，无向图无单向关系
triad_census(net)     #三元关系，共有16种类型，无向图无其中一部分关系
triangles(net)        #列举所有三元关系，数量等于第16类关系数*3
#count_triangles(net)  #所有三元关系所在组序号
```

```{r 网络群组}
largest_cliques(net)[[1]]  #全局最大群组
clique_num(net)            #全局最大群组的点数
max_cliques(net, subset = "CAPTAIN AMERICA")    #不同规模群组统计，不设定约束条件会运算很久
count_max_cliques(net, min = 10) #最大子群数量
```


```{r 特定点的关系和子图}
neighbors(net, v = "IRON MAN/TONY STARK") #邻居，去了重后不会有重复邻居出现，和degree的值相同
neighborhood.size(net, order = 2)         #每个点n步以内的邻居数量，1步以内邻居=degree
incident(net, v = "IRON MAN/TONY STARK")  #特定点的关系，和degree的值相同
ego(net, nodes = "IRON MAN/TONY STARK")   #个体网络
ego_size(net, nodes = "IRON MAN/TONY STARK")  #个体网络规模，= degree + 1
```


```{r 网络图可视化, fig.height=20, fig.width=20}
iron_man_graph <- make_ego_graph(net, nodes = "IRON MAN/TONY STARK")[[1]]  #需要提取第一个要素
iron_man_graph_100 <- induced_subgraph(iron_man_graph, degree(iron_man_graph) >= 100)  #按条件筛选对象
iron_man_graph
iron_man_graph_100
#lc <- induced_subgraph(net, largest_cliques(net)[[1]])
#lc
```


```{r 网络图可视化：Base R方法, fig.height=15, fig.width=20}
plot(iron_man_graph, 
     layout = layout_with_fr(iron_man_graph),
     vertex.size = 2,
     vertex.color = "blue",
     vertex.label = NA,
     edge.size = 0.1)

plot(iron_man_graph_100, 
     layout = layout_with_fr(iron_man_graph_100),
     vertex.size = 2,
     vertex.color = "blue",
     vertex.label = NA,
     edge.size = 0.1)
```

```{r 网络图可视化：ggraph方法, fig.height=15, fig.width=20}
ggraph(iron_man_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  theme_graph()    

ggraph(iron_man_graph_100, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), color = "blue") +
  theme_graph()
```

```{r 同类点的聚集程度}
assortativity_degree(net, directed = FALSE)
```


```{r 建立带有权重的新网络}
hero_network %>% 
  group_by(hero1, hero2) %>% 
  count() %>% 
  rename(weight = n) -> hero_network_weight
hero_network_weight

net_weight <- graph_from_data_frame(hero_network_weight, directed = FALSE)
net_weight
summary(E(net_weight)$weight)
list.vertex.attributes(net_weight)
list.edge.attributes(net_weight)

net_weight_sim <- igraph::simplify(net_weight) #简化网络，排除多次出现的关系以及自循环
net_weight_sim
summary(E(net_weight_sim)$weight)
```

```{r 网络转为数据框}
net_weight_df <- get.data.frame(net_weight, what = "edges") #默认为edges
net_weight_df
net_weight_df %>% arrange(desc(weight))

net_weight_sim_df <- get.data.frame(net_weight_sim) 
net_weight_sim_df %>% arrange(desc(weight))
```

```{r 利用点来源表生成网络}
edges %>%
  group_by(comic) %>%
  filter(n() > 1) %>%          
  split(.$comic) %>%          #按照comic进行分割
  map(., 1) %>%               #选择第1列
  map(~combn(.x, m = 2)) %>%  #在每个comic中用combin
  map(~t(.x)) %>%             #矩阵倒置
  map_dfr(as_tibble) %>%      #变为tibble
  rename(hero1 = V1, hero2 = V2) -> edges_hero_network
edges_hero_network #579,171种组合

edges %>% 
  group_by(comic) %>% 
  count() %>% 
  filter(n > 1) %>% 
  mutate(com_num = n * (n - 1) / 2) %>% 
  ungroup() %>% 
  summarise(total_com_num = sum(com_num)) #579171种组合
```

```{r 转换为有权重的网络}
edges_hero_network %>% 
  group_by(hero1, hero2) %>% 
  count() %>% 
  rename(weight = n) -> edges_hero_network_weight
edges_hero_network_weight
edges_net_weight <- graph_from_data_frame(edges_hero_network_weight, directed = FALSE)
edges_net_weight
edges_net_weight_sim <- igraph::simplify(edges_net_weight) #将所有自循环和相同关系（不论位置和权重）都剔除，权重会合并在一起
edges_net_weight_sim
summary(E(edges_net_weight_sim)$weight)
```

```{r 网络转化计数测试}
test <- data.frame(hero1 = c("a", "a", "b" , "c"), hero2 = c("b", "b", "a", "c"))
test %>% group_by(hero1, hero2) %>% count() %>% rename(weight = n) -> test_weight
test           #无权重
test_weight    #有权重

test_net_u <- graph_from_data_frame(test, directed = F)
test_net_u
igraph::simplify(test_net_u)

test_net_d <- graph_from_data_frame(test, directed = T)
test_net_d
igraph::simplify(test_net_d)

test_net_u_w <- graph_from_data_frame(test_weight, directed = F)
test_net_u_w
igraph::simplify(test_net_u_w)
E(test_net_u_w)$weight
E(igraph::simplify(test_net_u_w))$weight

test_net_d_w <- graph_from_data_frame(test_weight, directed = T)
test_net_d_w
igraph::simplify(test_net_d_w)
E(test_net_d_w)$weight
E(igraph::simplify(test_net_d_w))$weight
```

